### ISSUE TITLE
call interface

### ISSUE THREAD

**Issue by SilvaMendes** [emiago/diago#16]
Hi everyone, here's a discussion point.

I recently started testing Diago, and I decided to remove the media part, and added my API to rtpengine to test it. I managed to get the audio stream going through the proxy, but I came across a condition.

The calls are being forwarded inbound before bridging the channel, they go through a loop to a contact list, and I noticed that the calls originating from Diago.Server always use the same UDP port. Would this behavior be normal? Wouldn't this be a new one for each new call?

**Comment by emiago** [comment]
Hi @SilvaMendes , it is not TCP, and it is normal. You can make different port. Easiest is sip package has variable ConnectionReuse. Find that, and change value.

BTW it would be great that you share library for RTP engine.

**Comment by emiago** [comment]
@SilvaMendes It is normal behavior. You can force this on SIP level. Search ConnectionReuse . Although no big benefit for UDP.

**Comment by emiago** [comment]
it would be great that you share your API to rtpengine. I am open to have this documented in some way

**Comment by SilvaMendes** [comment]
https://pkg.go.dev/github.com/SilvaMendes/go-rtpengine

**Comment by emiago** [comment]
Awesome. Only comments on English and  examples would be a Must have if you want to push this project.
