### ISSUE TITLE
NewDiago replaces sipgo.Server's handlers

### ISSUE THREAD

**Issue by Qjawko** [emiago/diago#17]
Hi,

I am trying to customize the `OPTIONS` handler response to fit my specific requirements. However, when I call `diago.NewDiago` with my own `sipgo.Server` that has a defined `OPTIONS` handler, Diago overrides it with its own implementation.

I will submit a PR that modifies this behavior so that Diago checks for already registered methods and avoids replacing them.

Thank you!

**Comment by SilvaMendes** [comment]
but why didn't I add validation to server.OnInvite as well?

**Comment by Qjawko** [comment]
> but why didn't I add validation to server.OnInvite as well? Do you have an example of how you are customizing the methods?

I can, but I don't think that someone will need it, because diago already handles RTP streaming (inside sipgo handler) and other stuff.

Here is an example
```
srv, _ := sipgo.NewServer(ua)
	
srv.OnOptions(func(req *sip.Request, tx sip.ServerTransaction) {
	// do your stuff
})
	
dg := diago.NewDiago(ua, diago.WithServer(srv))
```

**Comment by SilvaMendes** [comment]
ok, i understand

**Comment by emiago** [comment]
works as intended. Thanks anyway for reporting this.
