### ISSUE TITLE
DTMF 0 is fired 3 times

### ISSUE THREAD

**Issue by shanehughes1990** [emiago/diago#21]
The following image shows when pressing 0 from my softphone calling into this server it is fired 3 times in quick succession, only that one input is like that.

This is the DTMF example almost literally with this tweaked in start func
```go
func start(ctx context.Context) error {
	// Setup our main transaction user
	media.RTPPortStart = 6000
	media.RTPPortEnd = 7000
	ua, _ := sipgo.NewUA()
	tu := diago.NewDiago(
		ua,
		diago.WithTransport(diago.Transport{
			Transport:    "udp",
			BindHost:     "0.0.0.0",
			ExternalHost: "REDACTED",
			BindPort:     5060,
		}),
	)

	return tu.Serve(
		ctx,
		func(inDialog *diago.DialogServerSession) {
			log.Info().Str("id", inDialog.ID).Msg("New dialog request")
			defer log.Info().Str("id", inDialog.ID).Msg("Dialog finished")

			ReadDTMF(inDialog)
		},
	)
}
```

![image](https://github.com/user-attachments/assets/22fc4235-da2a-4337-8885-7aa9a4a54fed)

**Comment by emiago** [comment]
Hi @shanehughes1990 . Any chance sending PCAP. Normally you receive multiple packets so could be some issue with filtering

**Comment by shanehughes1990** [comment]
Yeah I'll get a pcap going and upload it

**Comment by shanehughes1990** [comment]
I see there all detected multiple times, but only the 0 registers as 3 separate DTMF inputs on the server side.

When I do this same test same softphone with our production IVR I don't get 3 of each I get DTMF once, I'm guessing there's something weird going on with the diago server setup.

(0.7.0 is my diago version btw)

![image](https://github.com/user-attachments/assets/71656db2-abd8-4d67-ad53-fca2af7a844d)

**Comment by emiago** [comment]
@shanehughes1990 processing DTMF events may handle more corner cases. So in case you can reproduce, full PCAP would help. 
Also I think with DEBUG logging (zerolog) you may see this RTP events

**Comment by shanehughes1990** [comment]
Here's the Pcap for the above call.

[diago.pcap.zip](https://github.com/user-attachments/files/17790619/diago.pcap.zip)

**Comment by emiago** [comment]
great!

**Comment by emiago** [comment]
fixed on main

**Comment by emiago** [comment]
FYI this fix broke totally DTMF, now we have more tests arround this. 
Move to latest version

**Comment by shanehughes1990** [comment]
Thanks for the heads up.
