### ISSUE TITLE
EOF after 30 seconds of reading from RTPPacketReader

### ISSUE THREAD

**Issue by Qjawko** [emiago/diago#25]
Scenario:
When I'm trying to read from RTPPacketReader without any writes to RTPPacketWriter, after 30 seconds(or 248000 bytes) reader sends me an EOF error.

Version: v0.0.6. 
Tried to do the same scenario on newer versions(v0.7.1 and v0.8.0) but there are no any audio from RTPPacketReader(literally zero bytes from RTPPacketReader).

I'm using linphone app for Mac.

**Comment by emiago** [comment]
Hi @Qjawko , thanks for using libraries. It will be hard to know what is issue without more context. 
It is recomended to use at least `media.RTPBufSize` for reading. It should still be  no issue, but if reading is network, udps are framed.
There is now even gophone https://github.com/emiago/gophone using diago library for reading. 

You can try running gophone in similar enviroment and see if issue appears. 

Are you reading audio file or it is network stream?
Does using AudioReader makes difference? 
What is buffer size when you are reading?

**Comment by Qjawko** [comment]
```
func start(ctx context.Context) error {
	// Setup our main transaction user
	ua, _ := sipgo.NewUA()

	extHost := "127.0.0.1"
	if s := os.Getenv("EXTERNAL_HOST"); s != "" {
		extHost = s
	}

	tu := diago.NewDiago(ua, diago.WithTransport(diago.Transport{
		Transport:    "udp",
		BindHost:     "0.0.0.0",
		BindPort:     5060,
		ExternalHost: extHost,
		ExternalPort: 5060,
	}))

	return tu.Serve(ctx, func(inDialog *diago.DialogServerSession) {
		log.Info().Str("id", inDialog.ID).Msg("New dialog request")
		defer log.Info().Str("id", inDialog.ID).Msg("Dialog finished")
		err := ReadMedia(inDialog)
		if err != nil {
			log.Error().Err(err).Msg("ReadMedia")
		}
	})
}

func ReadMedia(inDialog *diago.DialogServerSession) error {
	var err error

	err = inDialog.Progress() // Progress -> 100 Trying
	err = inDialog.Answer()   // Answer -> 200 Response

	reader := inDialog.RTPPacketReader
	writer := inDialog.RTPPacketWriter

	n, err := media.CopyWithBuf(reader, writer, make([]byte, media.RTPBufSize))
	log.Info().Int64("bytes_sent", n).Msg("end call")

	return err
}
```

Here is my simple handler and server init. I'm just echoing all audio from RTPReader to RTPWriter with constant `media.RTPBufSize`.

On v0.6.0 on Mac works as expected. But with v0.8.0 on Mac there are no any data from RTPPackerReader, but on Ubuntu works as expected.

Will try to test with AudioReader.

**Comment by emiago** [comment]
Hi @Qjawko thanks for providing this. I am having hard time to understand what could be platform specific issue. 
Maybe it is something else. Can I suggest that you use sngrep tool (or any other pcap capture) check does RTP flowing (F3) or send me a pcap.

**Comment by Qjawko** [comment]
Hi @emiago, I've captured SIP call via wireshark and got this on v0.9.0 version. 
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/0440c037-42b3-4861-a755-a4d381e00b5a">

And with version v0.6.0 and sip-go v0.25.0 a lot less `Destination unreachable` errors.

Here is my captures, `090` and `060` in file names means diago version
[packet captures.zip](https://github.com/user-attachments/files/17991043/packet.captures.zip)

**Comment by emiago** [comment]
Hi @Qjawko can you send me on mail your pcap if you can. 
ICMP has nothing with diago

**Comment by Qjawko** [comment]
Hi @emiago, sorry for late responding. Pls check your mail. Thanks!

**Comment by emiago** [comment]
Hi @Qjawko . Can you disable STUN on your client and retest above. 
I guess this is something breaking media path.

**Comment by emiago** [comment]
No feedback on this. Please reopen if you have new info. 
It could be that stun signaling stops rtp readers. Would be great to see this with logs
