### ISSUE TITLE
"Received DTMF packet but short duration"

### ISSUE THREAD

**Issue by idontneedgithub** [emiago/diago#31]
DMTF example, MicroSIP as SIP client
It seems to "reject" repeated DTMF inputs, they get processed but don't reach the handler (111, 000, 222... stuff like 212 works though)

DBG Processing DTMF event ev={"Duration":1120,"EndOfEvent":false,"Event":1,"Volume":10}
DBG Processing DTMF event ev={"Duration":1280,"EndOfEvent":false,"Event":1,"Volume":10}
DBG Processing DTMF event ev={"Duration":1440,"EndOfEvent":false,"Event":1,"Volume":10}
DBG Processing DTMF event ev={"Duration":1600,"EndOfEvent":true,"Event":1,"Volume":10}
DBG Received DTMF packet but short duration dur=0

This is no matter the "dur" i set for AudioReaderDTMF.Listen

**Comment by idontneedgithub** [comment]
Commented out these lines

https://github.com/emiago/diago/blob/55bda19dc3ae05f5b34d96e1d7d6031014b7354b/media/rtp_dtmf_reader.go#L66-L68

Along with these

https://github.com/emiago/diago/blob/55bda19dc3ae05f5b34d96e1d7d6031014b7354b/media/rtp_dtmf_reader.go#L81-L83

Actually placed this at ~60ms instead

https://github.com/emiago/diago/blob/55bda19dc3ae05f5b34d96e1d7d6031014b7354b/media/rtp_dtmf_reader.go#L71

And it all seems to work fine

**Comment by emiago** [comment]
Aah crap we broke this with #21 

Thanks for reporting, now it is fixed on main -> v0.10.0 release
Please retest and reopen issue if not

**Comment by idontneedgithub** [comment]
Will do ASAP and report back to you
