### ISSUE TITLE
Strange context error on InviteBridge

### ISSUE THREAD

**Issue by yallxe** [emiago/diago#33]
Hi,
Just tried out the bridging example from here: https://github.com/emiago/diago/tree/main/examples/bridge
When using a domain name for the destination, I get this error:
```
go run ./examples/bridge sip:123123@sip.****.com
Dec 14 13:55:13.930521 INF Listening on transport addr=127.0.0.1:5060 protocol=udp
Dec 14 13:55:15.734859 INF IP addr resolving failed, doing via dns SRV resolver... error="lookup sip.****.com: operation was canceled"
```

I assume it can be something related to sipgo, but after some code analysis there I found nothing. I found no trace where the some context could be canceled.

**Comment by emiago** [comment]
Hi @yallxe  Thanks for reporting.
I see this only as DNS resolving failed on sipgo. Does not look as canceled from caller side yes.

**Comment by yallxe** [comment]
I probably now understand what happens. My SIP client could not find the codec in the response, and immediately sent BYE, therefore inCtx was canceled.
