### ISSUE TITLE
Golang UA with gui, using gio 

### ISSUE THREAD

**Issue by gedw99** [emiago/diago#7]
There are many UA phones out there and I think it’s quite easy to leverage all this golang code to make one built in golang with gio .

it can do voice on all platforms . Both desktop or mobile .

https://github.com/gioui

I use it quite a bit .

**Comment by emiago** [comment]
Hi @gedw99 . I already built something with `wails` , like GUI version for devs.
You can see mine CLI version of `https://github.com/emiago/gophone`  which probably more powerfull than any GUI can provide.

Still I am open suggestions, development, or consulting.  There are now I think 2 or 3 GUI GO frameworks. I used fyne as well, and built some file sharing app, but it is not good, not optimized and ect.. 
Please contact me on mail or DM on slack (Gophers workspace), I would like to hear your experience more.

**Comment by emiago** [comment]
Hi @gedw99 lets move then conversation. I have created meeting for reference and sent you link of chat room for just in case. I am alwasy open for this conversations.

**Comment by emiago** [comment]
@gedw99 if chat is standardized you would not care ;) Wait till you change your mind.
